# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

pr: none
trigger:
  - master

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Merge
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 60
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          source ./.ci-properties
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
          make generate sidetree-docker
          docker tag trustbloc/sidetree-mock:latest  trustbloc/sidetree-mock:$SIDETREE_MOCK_TAG
          docker push trustbloc/sidetree-mock:$SIDETREE_MOCK_TAG
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
